spring:
  profiles: 'dev'
  main:
      banner-mode: 'CONSOLE'
  datasource:
      url: 'jdbc:mysql://localhost:1433/cthteam'
      username: 'sa'
      password: 'Password_123'
      driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
      tomcat:
        max-wait: 10000
        max-active: 50
        test-on-borrow: true
  jpa:
      show-sql: true
      database-platform: 'org.hibernate.dialect.SQLServer2008Dialect'
      hibernate:
        ddl-auto: 'create'
server:
  port: 8080
  context-path: '/teamwork'
debug: true
logging:
  level:
    .: 'debug'
    org.springframework: 'debug'