spring:
  profiles: 'rsdev'
  main:
      banner-mode: 'CONSOLE'
  datasource:
      url: 'jdbc:mysql://localhost:4928/cthteam'
      username: 'root'
      password: 'root'
      driver-class-name: 'com.mysql.jdbc.Driver'
      tomcat:
        max-wait: 10000
        max-active: 50
        test-on-borrow: true
  jpa:
      show-sql: true
      database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      hibernate:
        ddl-auto: 'create'
server:
  port: 8181
  context-path: '/teamwork'
debug: true
logging:
  level:
    .: 'debug'
    org.springframework: 'debug'